#!/bin/sh
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"
cd "$(dirname "$0")/.."

# Perform lint check on files in the staging area through .lintstagedrc configuration
pnpm exec lint-staged
