**

!AcceptanceSpecSystem.sln
!Directory.Build.props
!src/
!src/**
!shared/
!shared/**

**/bin
**/obj
**/node_modules
**/dist
**/.vite
**/.testbin*
**/.testobj*
**/uploads
**/uploads/**
*.log
*.tmp
*.bak
