// 仅全局注册模板中实际使用的 Element Plus 组件。
// `web/tests/frontend-shell-guard.test.ts` 会校验此清单与源码标签保持一致。
import type { App, Component } from "vue";
import {
  ElAlert,
  ElBacktop,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElCard,
  ElCheckTag,
  ElCheckbox,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  ElConfigProvider,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElPagination,
  ElPopconfirm,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElOption,
  ElSkeleton,
  ElSlider,
  ElSteps,
  ElStep,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTabPane,
  ElTag,
  ElText,
  ElTimePicker,
  ElTree,
  ElUpload,
  ElSegmented,
  ElLoading
} from "element-plus";

const components = [
  ElAlert,
  ElBacktop,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElCard,
  ElCheckTag,
  ElCheckbox,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  ElConfigProvider,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElPagination,
  ElPopconfirm,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElOption,
  ElSkeleton,
  ElSlider,
  ElSteps,
  ElStep,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTabPane,
  ElTag,
  ElText,
  ElTimePicker,
  ElTree,
  ElUpload,
  ElSegmented
];

const plugins = [ElLoading];

/** 按需引入`element-plus` */
export function useElementPlus(app: App) {
  // 全局注册组件
  components.forEach((component: Component) => {
    if (component.name) {
      app.component(component.name, component);
    }
  });
  // 全局注册插件
  plugins.forEach(plugin => {
    app.use(plugin);
  });
}
